// ------------------------------------------------------------------ //
//  Rich per-module teaching content. The data in content/content.json
//  is generated by the 112-agent authoring workflow. Import this module
//  ONLY from Server Components so the (large) JSON never ships to the
//  client. Client components receive just what they render, as props.
// ------------------------------------------------------------------ //
import raw from "@/content/content.json";

export type CodeLang = "c" | "asm" | "bash" | "rust" | "" | string;

export interface Concept {
  name: string;
  explanation: string;
  codeExample?: string;
  codeLang?: CodeLang;
}

export interface Exercise {
  prompt: string;
  difficulty: "easy" | "medium" | "hard";
  hint?: string;
}

export type ResourceType =
  | "book"
  | "video"
  | "course"
  | "article"
  | "docs"
  | "tool"
  | "paper"
  | "interactive";

export interface Resource {
  title: string;
  type: ResourceType;
  url?: string;
  where?: string;
  free: boolean;
  note?: string;
}

export interface Diagram {
  title: string;
  mermaid: string;
  caption: string;
}

export interface ModuleContent {
  oneLiner: string;
  overview: string;
  whyItMatters: string;
  concepts: Concept[];
  keyInsights: string[];
  commonPitfalls: string[];
  diagram: Diagram;
  exercises: Exercise[];
  resources: Resource[];
  checkpoints: string[];
  estimatedHours: number;
}

const CONTENT = raw as Record<string, ModuleContent>;

export function getContent(id: string): ModuleContent | undefined {
  return CONTENT[id];
}

export function hasContent(id: string): boolean {
  return Boolean(CONTENT[id]);
}

export function contentCount(): number {
  return Object.keys(CONTENT).length;
}

export function totalEstimatedHours(): number {
  return Object.values(CONTENT).reduce(
    (sum, c) => sum + (typeof c.estimatedHours === "number" ? c.estimatedHours : 0),
    0,
  );
}

export function totalResources(): number {
  return Object.values(CONTENT).reduce(
    (sum, c) => sum + (Array.isArray(c.resources) ? c.resources.length : 0),
    0,
  );
}

export function totalConcepts(): number {
  return Object.values(CONTENT).reduce(
    (sum, c) => sum + (Array.isArray(c.concepts) ? c.concepts.length : 0),
    0,
  );
}
